Esri/arcgis-maps-sdk-kotlin-samples

settings.gradle
version.gradle

Updated `arcgisVersion` -> `200.0.0-beta01` beta release version and removed `olympus` atrifactory. The next release will be developed on the `v.next` branch. 
Sample Epic: `runtime/kotlin/issues/1617`

Release 200.0.0 beta 1

---

create-mobile-geodatabase/build.gradle
create-mobile-geodatabase/src/main/java/com/esri/arcgismaps/sample/createmobilegeodatabase/MainActivity.kt
navigate-route/build.gradle
navigate-route/src/main/java/com/esri/arcgismaps/sample/navigateroute/MainActivity.kt
set-up-location-driven-geotriggers/build.gradle
set-up-location-driven-geotriggers/src/main/java/com/esri/arcgismaps/sample/setuplocationdrivengeotriggers/MainActivity.kt
show-location-history/build.gradle
show-location-history/src/main/java/com/esri/arcgismaps/sample/showlocationhistory/MainActivity.kt
version.gradle

PR to replace and remove all references of Kotlin DateTime and replace them with Java Instant. 
Sample Epic: `runtime/kotlin/issues/2063`
- Check if the use of `Instant.now()` would be the right implementation. Or `Instant.EPOCH`

Replace DateTime with Instant

---

render-multilayer-symbols/src/main/java/com/esri/arcgismaps/sample/rendermultilayersymbols/MainActivity.kt
version.gradle

PR to fix the `PictureMarkerSymbolLayer` flaky loading behavior in the _Render multilayer symbols_ sample. 
Sample Epic: `runtime/kotlin/issues/2226 `

Render multilayer symbols patch

---

find-route-around-barriers/src/main/java/com/esri/arcgismaps/sample/findroutearoundbarriers/MainActivity.kt

PR to fix issue `runtime/kotlin/issues/2228`
The sample should inflate the bottom sheet with directions for at least two stops added to the map. 
But the sample seems to be displaying the sheet, even if stops are not added to the map.
Fix: the `directionsList` is created when 2 or more stops are added on the map. The directions sheet should only show up when the `directionsList` is not empty. 

show bottom sheet only when directions list is not empty

---

generate-geodatabase-replica-from-feature-service/src/main/java/com/esri/arcgismaps/sample/generategeodatabasereplicafromfeatureservice/MainActivity.kt
generate-geodatabase-replica-from-feature-service/src/main/res/layout/activity_main.xml
generate-geodatabase-replica-from-feature-service/src/main/res/values/strings.xml

This PR adds a red border similar to `Generate offline map` sample and implemented a reset button to clear map.
Sample Epic: `runtime/kotlin/issues/2373` 
Is it possible to create a geodatabase replica with just one layer? It would be helpful to speed up the sync task if we were to only create a replica for the "Trees" [layer](https://services2.arcgis.com/ZQgQTuoyBrtmoGdP/ArcGIS/rest/services/Mobile_Data_Collection_WFL1/FeatureServer/0). 
I tried the following implementation, but the task fails with an error: 
```kotlin
defaultParameters.layerOptions.add(GenerateLayerOption(layerId = 0))
```
Error:
```log
Error fetching geodatabase: Service error code 500: Unable to create replica. Please check your parameters.
Details:
Error in creating runtime geodatabase.
```

Generate geodatabase border

---

browse-building-floors/README.metadata.json
change-camera-controller/README.metadata.json
change-viewpoint/README.metadata.json
display-composable-mapview/README.metadata.json
display-device-location-with-nmea-data-sources/README.metadata.json
display-map/README.metadata.json
display-scene/README.metadata.json
manage-operational-layers/README.metadata.json
set-max-extent/README.metadata.json
set-up-location-driven-geotriggers/README.metadata.json
set-viewpoint-rotation/README.metadata.json
show-device-location-using-indoor-positioning/README.metadata.json
show-device-location/README.metadata.json
show-grid/README.metadata.json
show-location-history/README.metadata.json
show-magnifier/README.metadata.json
sketch-on-map/README.metadata.json
version.gradle

PR to update sample categories:
This issue is to update the relevant samples to their respective category names and update the sample viewer to the new category name changes
Sample Epic: `runtime/kotlin/issues/2748`

update sample categories

---

show-device-location-using-indoor-positioning/src/main/java/com/esri/arcgismaps/sample/showdevicelocationusingindoorpositioning/MainActivity.kt

The data source used in the sample has been modified and there are two tables in the currently used [portal item](https://www.arcgis.com/home/item.html?id=8fa941613b4b4b2b8a34ad4cdc3e4bba) (previously it was 1). The feature table used in this sample updated the name from: 
- `IPS_Positioning` -> `ips_positioning`
Sample issue: `runtime/kotlin/issues/2823`

IPS sample fix

---

display-points-using-clustering-feature-reduction/README.metadata.json

[Sample viewer build sample category crash](https://devtopia.esri.com/runtime/kotlin/issues/2926#issuecomment-4363153):
Fixes an error with sample viewer build caused by the feature reduction metadata file, with the order of the images file names.
Ran the sample viewer app, with this change to verify, and the Visualization category doesnt crash anymore.

fix sample viewer build "Visualization" category crash

---

generate-offline-map-using-android-jetpack-workmanager/src/main/AndroidManifest.xml
generate-offline-map-using-android-jetpack-workmanager/src/main/java/com/esri/arcgismaps/sample/generateofflinemapusingandroidjetpackworkmanager/OfflineJobWorker.kt

PR to fix the crashing of sample `generate-offline-map-using-android-jetpack-workmanager` when running on Android 14 (API level 34) devices.
#3463
- The correct ForegroundServiceType is used. View all available type [here](https://developer.android.com/develop/background-work/services/fg-service-types#data-sync).
- Sample `generate-offline-map-using-android-jetpack-workmanager` is running on both Android 13 and 14 devices, and the job can execute as expected.

Foreground service type patch - v.next

---

identify-layer-features/src/main/java/com/esri/arcgismaps/sample/identifylayerfeatures/components/MapViewModel.kt
identify-layer-features/src/main/java/com/esri/arcgismaps/sample/identifylayerfeatures/screens/MainScreen.kt

Revisit Identify layer features sample

---

query-feature-table/src/main/java/com/esri/arcgismaps/sample/queryfeaturetable/components/MapViewModel.kt
query-feature-table/src/main/java/com/esri/arcgismaps/sample/queryfeaturetable/screens/MainScreen.kt

Revisit query feature table sample

---

add-dynamic-entity-layer/src/main/java/com/esri/arcgismaps/sample/adddynamicentitylayer/components/BottomSheetContent.kt
authenticate-with-oauth/src/main/java/com/esri/arcgismaps/sample/authenticatewithoauth/OAuthUserSignInViewModel.kt
display-clusters/src/main/java/com/esri/arcgismaps/sample/displayclusters/components/ClusterInfoContent.kt
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
samples-lib/src/main/java/com/esri/arcgismaps/sample/sampleslib/DownloaderActivity.kt
samples-lib/src/main/java/com/esri/arcgismaps/sample/sampleslib/components/JobLoadingDialog.kt
settings.gradle.kts
show-device-location-using-indoor-positioning/src/main/java/com/esri/arcgismaps/sample/showdevicelocationusingindoorpositioning/MainActivity.kt
show-portal-user-info/src/main/java/com/esri/arcgismaps/sample/showportaluserinfo/screens/MainScreen.kt

PR to update the `v.next` branch to start using `200.5.0` daily builds. 
- `Divider` is deprecated, using `HorizontalDivider` instead.
- `AlertDialog` is deprecated, using `BasicAlertDialog ` instead.
- Some changes `LinearProgressIndicator` on the lastest compose version. 
- Updated `DownloaderActivity` and `JobLoadingDialog` to not be cancellable on back press

Update v.next for next release

---

geocode-offline/src/main/java/com/esri/arcgismaps/sample/geocodeoffline/MainActivity.kt
search-with-geocode/src/main/java/com/esri/arcgismaps/sample/searchwithgeocode/MainActivity.kt

PR to resolve bug that the textfield is not filled when choosing a text from suggestion list.
#3259
Sample `search-with-geocode` and `geocode-offline` run well. When selecting from the suggestion list, the selected text is filled in textfield and can search successfully.
Sample `search-with-geocode` and `geocode-offline` run well.

Bug: Update searchView query with selected suggestion result

---

show-line-of-sight-between-geoelements/src/main/java/com/esri/arcgismaps/sample/showlineofsightbetweengeoelements/DownloadActivity.kt

PR to add a copyright header to `DownloadActivity.kt` in sample `Show-Line-Of-Sight-Between-Geoelements`
Sample Epic: `runtime/kotlin/issues/ISSUE_NUMBER`
-  `DownloadActivity.kt` to verify that Esri copyright header exists

Show line of sight add copyright header

---

generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/components/MapViewModel.kt
generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/screens/MainScreen.kt

PR to fix a Kotlin sample _"GENERATE_OFFLINE_MAP"_ in `EDIT_AND_MANAGE_DATA` category.
Sample Epic: `runtime/kotlin/issues/ISSUE_NUMBER`
-  Review the changed/added code to make sure the changes wouldn't impact anything else and to see if sample code is easy to read.
- `MainScreen.kt` and `MapViewModel.kt` files
Run the sample on the sample viewer or the repo. 
1. When running it, the red border should always show on launch
2. After generating the offline map, and resettiing the map, the red border should show and stay the same size.

Fixed issue through adding onLayerViewStatechanged on MapView

---

create-and-save-map/src/main/java/com/esri/arcgismaps/sample/createandsavemap/MainActivity.kt

Updates Create and Save Map to unset API key & invalidate any existing OAuth credentials, making it play nice with the sample viewer.
Sample Epic: [#2922](https://devtopia.esri.com/runtime/kotlin/issues/2922)
- Is it sensible to use `runBlocking` like this? I had wanted to use `lifetimeScope`, but that caused the authenticator to loop indefinitely when re-running the sample in the viewer. This may cause a small delay when re-running the sample in the viewer.
- Does the sample work properly in the viewer?
- In particular, does it behave as expected before and after running "Authenticate with OAuth", which sets an API key and authenticates the user?
Run the sample in the sample …

[Patch] Create and save map

---

app/build.gradle.kts

PR to add singing instructions as a comment for clarity, rather than throwing an exception on each debug/release build. 
Issue: [#4597](https://devtopia.esri.com/runtime/kotlin/issues/4597)

Signing instructions

---

app/src/main/java/com/esri/arcgismaps/kotlin/sampleviewer/model/DefaultSampleInfoRepository.kt
app/src/main/java/com/esri/arcgismaps/kotlin/sampleviewer/model/SampleInfoRepository.kt
app/src/main/java/com/esri/arcgismaps/kotlin/sampleviewer/ui/screens/search/SearchSuggestionsScreen.kt

PR to fix the get sample usage using the sample title string for the `SearchSuggestionsList` screen

Fix get sample usage

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/esri/arcgismaps/kotlin/sampleviewer/MainActivity.kt
app/src/main/java/com/esri/arcgismaps/kotlin/sampleviewer/SampleViewerApplication.kt
app/src/main/java/com/esri/arcgismaps/kotlin/sampleviewer/model/DefaultSampleInfoRepository.kt

Explored dependency injection, which would require importing dagger/hilt and is probably beyond min ship.
How's this for a simple check to prevent repeat calls to load logic?

Simple fix to not re-running load

---

samples/analyze-network-with-subnetwork-trace/src/main/java/com/esri/arcgismaps/sample/analyzenetworkwithsubnetworktrace/MainActivity.kt

PR to fix crash on Analyze-network-with-subnetwork-trace sample when adding a value transition. My guess is this is due to changes in  Kotlin `objectInstance`. 
- Test if the sample works as expected.

Fix Analyze-network-with-subnetwork-trace sample

---

samples/display-dimensions/README.md

The `GeodatabaseSyncTask` link in the README for **Display dimensions** sample points to the Maps SDK for Java API Ref, instead of the Maps SDK for Kotlin API Ref. And even with that wrong target, the link is broken.
- https://next.sites.afd.arcgis.com/kotlin/sample-code/display-dimensions/#additional-information
Verify that the `GeodatabaseSyncTask` link goes to the Kotlin API Ref.
Click the link. See where it goes. It should go to https://developers.arcgis.com/kotlin/api-reference/arcgis-maps-kotlin/com.arcgismaps.tasks.geodatabase/-geodatabase-sync-task/index.html

Fix GeodatabaseSyncTask link so it points to Kotlin API Ref instead of Java API Ref

---

samples/clip-geometry/src/main/java/com/esri/arcgismaps/sample/clipgeometry/screens/ClipGeometryScreen.kt
samples/clip-geometry/src/main/res/values/strings.xml

Fix simple typo in clip geometry sample's strings ("rest_button_text" -> "reset_button_text")
Run sample on sample viewer if necessary

Fix typo in reset button string

---

samples/add-feature-layers/src/main/java/com/esri/arcgismaps/sample/addfeaturelayers/DownloadActivity.kt
samples/add-features-with-contingent-values/src/main/java/com/esri/arcgismaps/sample/addfeatureswithcontingentvalues/DownloadActivity.kt
samples/apply-dictionary-renderer-to-feature-layer/src/main/java/com/esri/arcgismaps/sample/applydictionaryrenderertofeaturelayer/DownloadActivity.kt
samples/display-device-location-with-nmea-data-sources/src/main/java/com/esri/arcgismaps/sample/displaydevicelocationwithnmeadatasources/DownloadActivity.kt
samples/display-dimensions/src/main/java/com/esri/arcgismaps/sample/displaydimensions/DownloadActivity.kt
samples/find-route-in-transport-network/src/main/java/com/esri/arcgismaps/sample/findrouteintransportnetwork/DownloadActivity.kt
samples/geocode-offline/src/main/java/com/esri/arcgismaps/sample/geocodeoffline/DownloadActivity.kt

Some copies of `DownloadActivity` were missing a copyright header. This PR adds them in with the correct date for each sample.
Sample Epic: `runtime/kotlin/issues/ISSUE_NUMBER`

Add copyright header to DownloadActivity

---

.gitignore
app/src/main/java/com/esri/arcgismaps/kotlin/sampleviewer/SampleViewerLauncherActivity.kt
app/src/main/java/com/esri/arcgismaps/kotlin/sampleviewer/model/DefaultSampleInfoRepository.kt
app/src/main/java/com/esri/arcgismaps/kotlin/sampleviewer/model/Sample.kt
gradle-plugins/build.gradle.kts
gradle-plugins/settings.gradle.kts
gradle-plugins/src/main/kotlin/com/arcgismaps/CopySampleFilesTask.kt

PR to address build files source code misleading android studio. The changes in this PR aims to not use local copied files, but instead maintain a JSON sample asset data with all (100) samples assets in a `sampleAssets/samples.json`:  
```json
{
"sampleA": {
"MainActivity.kt": "...content...",
"README.md": "...content...",
...
},
"sampleB": {
...
}
}
```
- Note: Run a build `clean` before running the changes in this branch. 
Sample Epic: [#5467](https://devtopia.esri.com/runtime/kotlin/issues/5467)

Sample build JSON asset data

---

gradle/libs.versions.toml
samples/augment-reality-to-show-tabletop-scene/src/main/AndroidManifest.xml
samples/augment-reality-to-show-tabletop-scene/src/main/java/com/esri/arcgismaps/sample/augmentrealitytoshowtabletopscene/MainActivity.kt

PR to make the AR module an optional module for the sample viewer and add logic to handle the scenario if the device does not support AR. 
Sample Epic: #[5638](https://devtopia.esri.com/runtime/kotlin/issues/5638)

Make AR module optional for the sample viewer

---

settings.gradle.kts

Updates the logic used to set Artifactory information to use command-line parameters first, then local.properties second.
- [Issue - DevOps](https://devtopia.esri.com/runtime/devops/issues/4181), [Issue - Kotlin](https://devtopia.esri.com/runtime/kotlin/issues/5058)
N/A
N/A

Get Artifactory info from local.properties

---

build-logic/convention/build.gradle.kts
gradle-plugins/build.gradle.kts
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties

PR to update gradle version to `8.14` (& fix new deprecation)
Sample issue: [#5714](https://devtopia.esri.com/runtime/kotlin/issues/5714)

Update to gradle 8.14

---

samples/augment-reality-to-navigate-route/src/main/java/com/esri/arcgismaps/sample/augmentrealitytonavigateroute/MainActivity.kt
samples/augment-reality-to-navigate-route/src/main/java/com/esri/arcgismaps/sample/augmentrealitytonavigateroute/components/AugmentedRealityViewModel.kt
samples/augment-reality-to-navigate-route/src/main/java/com/esri/arcgismaps/sample/augmentrealitytonavigateroute/components/SharedRepository.kt
samples/augment-reality-to-navigate-route/src/main/java/com/esri/arcgismaps/sample/augmentrealitytonavigateroute/screens/AugmentedRealityScreen.kt
samples/augment-reality-to-show-hidden-infrastructure/src/main/java/com/esri/arcgismaps/sample/augmentrealitytoshowhiddeninfrastructure/MainActivity.kt
samples/augment-reality-to-show-hidden-infrastructure/src/main/java/com/esri/arcgismaps/sample/augmentrealitytoshowhiddeninfrastructure/components/AugmentedRealityViewModel.kt
samples/augment-reality-to-show-hidden-infrastructure/src/main/java/com/esri/arcgismaps/sample/augmentrealitytoshowhiddeninfrastructure/components/SharedRepository.kt
samples/augment-reality-to-show-hidden-infrastructure/src/main/java/com/esri/arcgismaps/sample/augmentrealitytoshowhiddeninfrastructure/screens/AugmentedRealityScreen.kt

Enhance AR samples to better handle geospatial API key and VPS availability
- Does the sample correctly start you in Geospatial or World scale mode with/without a google geospatial API key present?
- Does the UI correctly update when VPS is available (when near google street view data) or not?

AR sample enhancements: handle geospatial API key and show VPS availability

---

gradle/libs.versions.toml
samples/authenticate-with-oauth/src/main/java/com/esri/arcgismaps/sample/authenticatewithoauth/components/MapViewModel.kt
samples/create-and-save-map/src/main/java/com/esri/arcgismaps/sample/createandsavemap/components/MapViewModel.kt
samples/show-portal-user-info/src/main/java/com/esri/arcgismaps/sample/showportaluserinfo/components/AppViewModel.kt

Replace deprecated oAuth assignment now to by list

Change deprecated call for OAuthUserConfiguration

---

gradle/libs.versions.toml
samples-lib/build.gradle.kts

Based on [this](https://developer.android.com/jetpack/androidx/releases/lifecycle#2.8.0) "lifecycle-runtime-ktx is now empty, with all APIs being moved into lifecycle-runtime." remove uses of androidx.lifecycle:lifecycle-runtime-ktx 
vTest - https://runtime-kotlin.esri.com/job/200.8.0/job/vtest/job/sampleviewer/1/console

Remove use of androidx.lifecycle:lifecycle-runtime-ktx

---

app/build.gradle.kts
build-logic/convention/src/main/java/ArcGISMapsKotlinSampleConventionPlugin.kt
build.gradle.kts

PR to fix `-D build=200.x` build flag:
```cmd
./gradlew assembleDebug -D build=200.8.0-4665 
```
Sample issue: [#6228](https://devtopia.esri.com/runtime/kotlin/issues/6228)

Fix `-D build=200.x` build flag

---

samples/augment-reality-to-navigate-route/src/main/AndroidManifest.xml
samples/augment-reality-to-show-hidden-infrastructure/src/main/AndroidManifest.xml

PR to remove unused permission declaration `ACCESS_BACKGROUND_LOCATION` from the sample viewer.

Remove unused permission declaration

---

samples/take-screenshot/src/main/AndroidManifest.xml
samples/take-screenshot/src/main/java/com/esri/arcgismaps/sample/takescreenshot/components/TakeScreenshotViewModel.kt
samples/take-screenshot/src/main/java/com/esri/arcgismaps/sample/takescreenshot/screens/TakeScreenshotScreen.kt

PR to update the sample Take Screenshot to only use `WRITE_EXTERNAL_STORAGE` permission for API 28. See [Android docs](https://developer.android.com/about/versions/14/changes/partial-photo-video-access). 
> As of Android 10 (API level 29), apps no longer need storage permissions to add files to shared storage. This means that apps can add images to the gallery, record videos and save them to shared storage, or download PDF invoices without having to request storage permissions. If your app only adds files to shared storage and doesn't query images or videos, you should stop requesting storage permissions and set a maxSdkVersion of API 28 in your AndroidManifest.xml:

Take screenshot permission fix
