Esri/arcgis-maps-sdk-kotlin-samples

cut-geometry/src/main/java/com/esri/arcgismaps/sample/cutgeometry/MainActivity.kt, settings.gradle, style-graphics-with-renderer/build.gradle, style-graphics-with-renderer/src/main/java/com/esri/arcgismaps/sample/stylegraphicswithrenderer/MainActivity.kt, version.gradle
PR to resolve breaking changes in the latest version of the Maps SDK for the `v.next` branch. 
Kotlin Issue: `runtime/kotlin/issues/1624`
-  Samples build and run fine with the latest version
=> Resolve version update breaking changes

clip-geometry/src/main/java/com/esri/arcgismaps/sample/clipgeometry/MainActivity.kt, clip-geometry/src/main/res/layout/activity_main.xml
PR to add a reset button to the existing `Clip Geometry` sample. https://devtopia.esri.com/runtime/kotlin/issues/1625
MainActivity.kt and the activity_main.xml file
Run the sample using the branch.
=> Update Clip Geometry Sample

apply-function-to-raster-from-service/src/main/java/com/esri/arcgismaps/sample/applyfunctiontorasterfromservice/MainActivity.kt, generate-offline-map-using-android-jetpack-workmanager/src/main/java/com/esri/arcgismaps/sample/generateofflinemapusingandroidjetpackworkmanager/OfflineJobWorker.kt, render-multilayer-symbols/src/main/java/com/esri/arcgismaps/sample/rendermultilayersymbols/MainActivity.kt, set-up-location-driven-geotriggers/src/main/java/com/esri/arcgismaps/sample/setuplocationdrivengeotriggers/MainActivity.kt, show-location-history/src/main/java/com/esri/arcgismaps/sample/showlocationhistory/MainActivity.kt, version.gradle
PR to update samples to reflect the `3823` build changes. 
Sample Epic: `runtime/kotlin/issues/2097`
=> Apply build changes

navigate-route/src/main/java/com/esri/arcgismaps/sample/navigateroute/MainActivity.kt, set-up-location-driven-geotriggers/src/main/java/com/esri/arcgismaps/sample/setuplocationdrivengeotriggers/MainActivity.kt, version.gradle
PR to update samples to reflect the `3834` build changes. 
Sample Epic: `runtime/kotlin/issues/2097`
=> Build changes

set-up-location-driven-geotriggers/src/main/java/com/esri/arcgismaps/sample/setuplocationdrivengeotriggers/FeatureListAdapter.kt
Added a fix to the sample to invoke the correct click listener. 
Sample issue: `runtime/kotlin/issues/2822 `
=> Geotriggers feature click fix

authenticate-with-oauth/src/main/AndroidManifest.xml, authenticate-with-oauth/src/main/java/com/esri/arcgismaps/sample/authenticatewithoauth/MainActivity.kt, authenticate-with-oauth/src/main/res/values/strings.xml
PR to fix sample viewer naming conflicts for the two authentication samples. 
`runtime/kotlin/issues/3098`
=> Patch authentication samples

.github/workflows/main.yml
PR to update the metadata script checker to run when targeting the `feature-branch/geo-compose` branch.
=> Update metadata script checker 

gradle/libs.versions.toml, show-result-of-spatial-operations/build.gradle.kts
PR to resolve build errors for the sample viewer. 
`runtime/kotlin/issues/3513 `
=> Samples DSL migration patch

add-dynamic-entity-layer/src/main/java/com/esri/arcgismaps/sample/adddynamicentitylayer/components/BottomSheetContent.kt, add-dynamic-entity-layer/src/main/java/com/esri/arcgismaps/sample/adddynamicentitylayer/components/MapViewModel.kt, add-dynamic-entity-layer/src/main/java/com/esri/arcgismaps/sample/adddynamicentitylayer/screens/MainScreen.kt
=> Update Add Dynamic Entity Layer sample

display-points-using-clustering-feature-reduction/src/main/java/com/esri/arcgismaps/sample/displaypointsusingclusteringfeaturereduction/components/MapViewModel.kt, display-points-using-clustering-feature-reduction/src/main/java/com/esri/arcgismaps/sample/displaypointsusingclusteringfeaturereduction/screens/MainScreen.kt
=> Update Feature clustering sample

manage-operational-layers/src/main/java/com/esri/arcgismaps/sample/manageoperationallayers/components/MapViewModel.kt, manage-operational-layers/src/main/java/com/esri/arcgismaps/sample/manageoperationallayers/screens/MainScreen.kt
=> Update manage operational layers sample

gradle/libs.versions.toml
PR to fix daily builds, and only depend on one version for both Toolkit and SDK.
=> SDK version

README.md, build.gradle.kts
PR to update API key instructions to point to the new developer [Create an API Key](https://links.esri.com/create-an-api-key) page. 
Issue: `kotlin/issues/3980`
=> Citra update instructions

add-custom-dynamic-entity-data-source/README.metadata.json
Fix device provisioning for this sample due to file rename
=> customDynamicEntityDeviceProvisonFix

configure-basemap-style-parameters/src/main/java/com/esri/arcgismaps/sample/configurebasemapstyleparameters/MainActivity.kt, configure-clusters/src/main/java/com/esri/arcgismaps/sample/configureclusters/screens/MainScreen.kt, create-planar-and-geodetic-buffers/src/main/java/com/esri/arcgismaps/sample/createplanarandgeodeticbuffers/MainActivity.kt, edit-feature-attachments/src/main/java/com/esri/arcgismaps/sample/editfeatureattachments/AttachmentsBottomSheet.kt, edit-feature-attachments/src/main/res/layout/attachment_edit_sheet.xml, find-closest-facility-from-point/README.md, generate-offline-map-using-android-jetpack-workmanager/src/main/java/com/esri/arcgismaps/sample/generateofflinemapusingandroidjetpackworkmanager/WorkerNotification.kt, generate-offline-map-using-android-jetpack-workmanager/src/main/res/layout/activity_main.xml, gradle/libs.versions.toml, navigate-route/src/main/java/com/esri/arcgismaps/sample/navigateroute/MainActivity.kt, project-geometry/src/main/java/com/esri/arcgismaps/sample/projectgeometry/MainActivity.kt, samples-lib/src/main/java/com/esri/arcgismaps/sample/sampleslib/components/BottomSheet.kt, samples-lib/src/main/res/values/strings.xml, snap-geometry-edits/src/main/java/com/esri/arcgismaps/sample/snapgeometryedits/screens/MainScreen.kt
=> Release code cleanup

add-kml-layer-with-network-links/README.metadata.json
PR to set the `MainActivity` as the launcher for SV.
Sample issue: [#1763](https://devtopia.esri.com/runtime/kotlin/issues/1763) 
=> Kml sample fix

samples/add-enc-exchange-set/src/main/res/values/strings.xml, samples/create-and-save-map/src/main/res/values/strings.xml, samples/display-composable-mapview/src/main/java/com/esri/arcgismaps/sample/displaycomposablemapview/MainActivity.kt, samples/display-composable-mapview/src/main/res/values/strings.xml, samples/show-line-of-sight-between-geoelements/src/main/res/values/strings.xml, samples/show-magnifier/src/main/res/values/strings.xml, samples/snap-geometry-edits/src/main/res/values/strings.xml
Sample names spotted with incorrect casing
=> change to sentence case

app/build.gradle.kts
PR to add  `x86_64` ABI support for samples project.
=> Add x86_64 ABI support

app/build.gradle.kts, gradle/libs.versions.toml, settings.gradle.kts
PR to include 200.6.0 release changes for the release branch
Issue: [#4906](https://devtopia.esri.com/runtime/kotlin/issues/4906)
=> 200.6.0 Release Changes

build-logic/convention/src/main/java/com/esri/arcgismaps/kotlin/build_logic/convention/KotlinAndroid.kt, samples-lib/src/main/java/com/esri/arcgismaps/sample/sampleslib/DownloaderActivity.kt, samples-lib/src/main/java/com/esri/arcgismaps/sample/sampleslib/components/BottomSheet.kt, samples/add-custom-dynamic-entity-data-source/src/main/java/com/esri/arcgismaps/sample/addcustomdynamicentitydatasource/components/CustomEntityFeedProvider.kt, samples/add-kml-layer-with-network-links/src/main/java/com/esri/arcgismaps/sample/addkmllayerwithnetworklinks/components/SceneViewModel.kt, samples/cut-geometry/src/main/java/com/esri/arcgismaps/sample/cutgeometry/MainActivity.kt, samples/edit-features-using-feature-forms/src/main/java/com/esri/arcgismaps/sample/editfeaturesusingfeatureforms/screens/MainScreen.kt, samples/manage-operational-layers/src/main/java/com/esri/arcgismaps/sample/manageoperationallayers/screens/LayersList.kt, samples/render-multilayer-symbols/src/main/java/com/esri/arcgismaps/sample/rendermultilayersymbols/MainActivity.kt, samples/style-graphics-with-renderer/src/main/java/com/esri/arcgismaps/sample/stylegraphicswithrenderer/MainActivity.kt
PR to remove unused resources and added some lint corrections found using Inspect Code.
- These changes will be added to the `release/200.6.0` branch once merged to `v.next`. 
Issue: [#4906](https://devtopia.esri.com/runtime/kotlin/issues/4906)
=> Inspect Code & Lint Corrections

tools/CI/README_Metadata_StyleCheck/metadata_style_checker.py
Update metadata checker to expect view model first
=> update script to expect view model first

app/build.gradle.kts, app/src/main/java/com/esri/arcgismaps/kotlin/sampleviewer/ui/screens/home/HomeCategoryScreen.kt
Display dialog if an API key is not set prompting the user to set an API key.
Issue: [Link](https://devtopia.esri.com/runtime/kotlin/issues/5019)
=> Report if key is not set

app/build.gradle.kts, app/src/main/java/com/esri/arcgismaps/kotlin/sampleviewer/ui/screens/home/HomeCategoryScreen.kt
=> CherryPick: API key not set

samples/display-dimensions/README.md
Cherry pick #279  to release branch.
=> CherryPick doc link

samples/display-web-scene-from-portal-item/src/main/AndroidManifest.xml
PR to fix the issue with our daily build.
=> Daily build patch

samples/create-and-edit-geometries/src/main/java/com/esri/arcgismaps/sample/createandeditgeometries/components/CreateAndEditGeometriesViewModel.kt, samples/create-and-edit-geometries/src/main/java/com/esri/arcgismaps/sample/createandeditgeometries/screens/ButtonMenu.kt, samples/create-and-edit-geometries/src/main/java/com/esri/arcgismaps/sample/createandeditgeometries/screens/CreateAndEditGeometriesScreen.kt, samples/create-and-edit-geometries/src/main/res/drawable/redo_24.xml, samples/create-and-edit-geometries/src/main/res/drawable/undo_24.xml
Adding more functionality to the create and edit geometries working branch
Issues: https://devtopia.esri.com/runtime/kotlin/issues/2921, https://devtopia.esri.com/runtime/kotlin/issues/5255
vTest: https://runtime-kotlin.esri.com/view/all/job/vtest/job/sampleviewer/75/
Review like ordinary sample. The delete button is of particular interest since a new dropdown was added to try make it fit and have sufficient detail on what it does. Will fail style checks as README will likely be part of final stage.
=> Create and edit geometries second stage

samples/snap-geometry-edits-with-utility-network-rules/src/main/java/com/esri/arcgismaps/sample/snapgeometryeditswithutilitynetworkrules/components/SnapGeometryEditsWithUtilityNetworkRulesViewModel.kt, samples/snap-geometry-edits-with-utility-network-rules/src/main/java/com/esri/arcgismaps/sample/snapgeometryeditswithutilitynetworkrules/screens/SnapGeometryEditsWithUtilityNetworkRulesScreen.kt, samples/snap-geometry-edits-with-utility-network-rules/src/main/java/com/esri/arcgismaps/sample/snapgeometryeditswithutilitynetworkrules/screens/SnapSourcesPanel.kt
PR to _composify_ the UI workflow for the Snap geometry edits with utility network rules sample.
=> Snap Utility UI

samples/snap-geometry-edits/README.md
PR to update the Readme file in the `Snap Geometry Edits` existing sample.
As discussed @TADraeseke , this is a minor update to the readme only (no code additions, so we have not added any new API tags for example as they are not used in the sample code). If it's reasonable to include in the release at this point then please go ahead and merge at your convenience.
Issue: https://devtopia.esri.com/runtime/bistromath/issues/3151
A [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/sampleviewer/) Job for this PR has been run
-  Review the README change - it should correspond to the designed change in the linked issue.
=> Add comment about child snap sources

gradle-plugins/src/main/kotlin/com/arcgismaps/CopySampleFilesTask.kt
PR to add a fix for sample list sorting. 
=> Added sortedBy to asset list

samples/augment-reality-to-show-tabletop-scene/src/main/java/com/esri/arcgismaps/sample/augmentrealitytoshowtabletopscene/MainActivity.kt, tools/CI/README_Metadata_StyleCheck/Dockerfile.dockerfile
Update docker alpine:3.19 to use ruby 3.0
=> Update docker alpine:3.19 to use ruby 3.0 

samples/augment-reality-to-navigate-route/README.md, samples/augment-reality-to-navigate-route/README.metadata.json, samples/augment-reality-to-show-hidden-infrastructure/README.md, samples/augment-reality-to-show-tabletop-scene/README.md, samples/authenticate-with-oauth/README.md, samples/create-and-save-map/README.md, samples/edit-features-using-feature-forms/README.md, samples/show-popup/README.md, samples/show-portal-user-info/README.md, samples/show-scale-bar/README.md
Update toolkit module reference doc
NOTE: Readme checker is complaining about class ordering in metdata, but for that sample, I think it is worth having the AR view model first
=> Point towards toolkit docs
